# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7457fadac3a5b09c0afa09a1de2327f84180d141df6f84a47dc3d591c3a5dec42ed07b8842040d8326baddc84c119f30e3105277eed0effde59363eb9640f954

test:
  secret_key_base: f9c808f6d07e07610ba3680d2f65fe7ec43b8cf55f52a1eb07dd6490f46025d4c8722cd8b36b5e0f4a533eaa1267bde05dbc7c270f4c1c3ebe4afa89cc4e239f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
